### PR TITLE
refactor: optimize webpack config for html-bundler-webpack-plugin

### PR DESCRIPTION
**Pull request by webdiscus**
Hello @sneas,

thanks for the cool slider.

I'm the author of the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin).

I tried to optimise the Webpack config for the demo page in `packages/www/` and want to demonstrate the universal `html-bundler-webpack-plugin` that simplify the Webpack configuration to generate HTML with assets from source files (templates , scripts, styles, images, fonts, etc.).

I grouped the source files to optimise the configuration and added the `watchFiles` option for Live Reload after changes.

The `html-bundler-webpack-plugin` is the best modern alternative to `html-webpack-plugin`.

### Using the bundler plugin:
- An entry point is an HTML template.
- Source scripts and styles can be specified directly in HTML using `<script>` and `<link>` tags.
- Resolving source assets specified in attributes `href` `src` `srcset` etc.
- Inline JS, CSS, SVG, PNG without additional plugins and loaders.
- Can be used any templating engine:  EJS, Handlebars, Nunjucks, etc.

### Your profit

- all the source scripts and styles can be specified in one right place, in HTML, no need to define them in Webpack entry or import SCSS in JS file
- in generated HTML all source files (scripts, styles, fonts, images) used in a template will be replaced with output filenames. No need to use the copy plugin.
- just one plugin replaces the functionality of many plugins and loaders such as:
   - html-webpack-plugin
   - mini-css-extract-plugin
   - handlebars-loader
   - resolve-url-loader
   - style-loader
   - copy-webpack-plugin

### How to test

You can try the [forked repo](https://github.com/webdiscus/img-comparison-slider)
```
git clone https://github.com/webdiscus/img-comparison-slider.git
cd img-comparison-slider
npm i
npm start
```

### CODE REVIEW

**Comment by sneas** [comment]
Hi @webdiscus, looks nice! Unfortunately, `npm run build` run in `packages/www` folder ends up with error `TypeError: str.replace is not a function`. Do you have it on your machine as well?

**Comment by webdiscus** [comment]
Hi @sneas,

ah, sorry.  There was a conflict when using the copy plugin with enabled minify.  I have updated the plugin.
Now `npm run build` works.

**Comment by sneas** [comment]
@webdiscus, thanks a lot for the PR 👍

**Pull request merged**
