### PR TITLE
feat: handle attribute

### LINKED ISSUE #99: How to change the slider position only by dragging the handle, and set hover effect to the second slot
As the video, how to trigger slider only by dragging the handle and get "--exposure" value in the second element to set block width for hover

https://user-images.githubusercontent.com/38325453/195651743-afb36a31-b4b4-4bfd-92bd-185fa9b2c387.mov

### PR DESCRIPTION
**Pull request by sneas**
fix #99

### CODE REVIEW

**Comment by JarvisChao** [comment]
> If you update the library to `v7.8.0`, you can set the `handle` attribute on the component. Something like that``. This will make the slider move only by the handle. Unfortunately, I have no easy recipe for making hover functionality work on the second slot but not on the first slot + the handle attribute is enabled. This will require some refactoring. I'm not ready for this right now.

Hi~
After testing, I found that there have dragging problems in the mobile.

https://user-images.githubusercontent.com/38325453/198326200-a3191331-35e8-464f-a049-5ffea2ca82c9.mov

Got this error message in the console.

截圖 2022-10-27 23 12 11

**Comment by sneas** [comment]
Thank you, @JarvisChao 👍 I've just released a new library version, which is fixing the problem you've reported.

**Comment by JarvisChao** [comment]
> Thank you, @JarvisChao 👍 I've just released a new library version, which is fixing the problem you've reported.

I appreciate it !

**Pull request merged**
